REVIEW: get_sections()
palaeoverse/rmacrostrat pull request #33
Opened 2024-06-11 13:17 UTC by bethany-j-allen

Hi all, as this is the final one of the big three functions to be reviewed, I also tried to get them to align a little better. As such I changed some of the phrasing of the definitions so they match. A few things it would be good to discuss:
* Do we want to thoroughly check consistency between these three functions, or is it fine as long as they have all been reviewed?
* I reordered a couple of the arguments so that these match (according to what we agreed at the end of the week, I think). Are we happy with this?
* The current description of `econ$prop` in the returned `df` is a bit awkward. Is this the proportion of the section/column thought to contain the specific resource?
* Do we want to align the examples? I think we should at least have the same number of examples for each.

2024-06-11 14:22 UTC, willgearty commented on R/get_sections.R
> +#'        potential economic attributes contained within the section, calculated
```suggestion
#'        all economic attributes contained within the section, calculated
```

2024-06-11 14:37 UTC, willgearty commented
Thanks for doing this slightly broader review @bethany-j-allen! I agree with all of the changes you made and appreciate you making these functions a bit more aligned. I don't think they need to be exactly one-to-one (e.g., examples) because they do have different arguments and returned values, but aligning the documentation that is shared would be good.

For `econ`, the `prop` values always add up to 1. Therefore I don't think this is the proportion of the section that is thought to contain this resource. My guess is that it is the proportion of units (in the case of `get_sections()` or `get_columns()`) containing a resource that contain that specific resource? But your guess is as good as mine...

2024-06-13 11:08 UTC, LewisAJones approved these changes
Hi Bethany, some very tiny comments, but great job on further standardising things across functions! I agree with Will that we don't need to have the same number of examples across functions as this is going to be very dependent on available functionality. I am also not 100% clear on the `econ$prop` here... Will is probably right in that it is likely related to the proportion of units, but whether this is based on the number of units, their thickness, or age duration within each section/column is unclear to me (one would hope thickness?).

2024-06-13 11:08 UTC, LewisAJones commented on R/get_units.R
> +                      econ_class = NULL, project_id = NULL, adjacents = NULL,
Should adjacents actually default to FALSE here? It's a logical argument?

2024-06-13 16:11 UTC, ChristopherDavidDean requested changes
Hi Bethany, thanks so much for taking the hit and synonymising these files, it's really appreciated. Put some minor comments here on there on small things to change, but otherwise I think it looks good. RE the proportions, I get the feeling that it averages out the proportions for each unit, rather than by thickness/time, but where those individual units get their proportions lord knows.

2024-06-13 16:11 UTC, ChristopherDavidDean commented on R/get_columns.R
> +#'      continuous time age model, in millions of years before present.
This should be changed to 'age of the bottom of the column', as get_columns() returns info for an entire column.

2024-06-13 16:11 UTC, ChristopherDavidDean commented on R/get_columns.R
> +#'   \item \code{t_age}: The age of the top of the unit, estimated using the
This should be changed to 'age of the top of the column', as get_columns() returns info for an entire column.

2024-06-13 16:11 UTC, ChristopherDavidDean commented on R/get_sections.R
> +#'   unit that matches a stratigraphic name (e.g., "Hell Creek").
As @willgearty mentioned above, this should probably be kept.

2024-06-13 16:11 UTC, ChristopherDavidDean commented on R/get_sections.R
> +#'     column.
Maybe change to "The unique identification number of the Macrostrat column containing the section" just to make the distinction between these super clear?

2024-06-13 16:11 UTC, ChristopherDavidDean commented on R/get_sections.R
>  #'   \item \code{col_area}: The area of the Macrostrat column in
Same here - maybe "The area of the associated Macrostrat column..." is best.

2024-06-13 16:11 UTC, ChristopherDavidDean commented on R/get_sections.R
> +#' # Get sections within a specified latitude-longitude box
I think this is from a specific lat/long coordinate point, not an associated box.

2024-06-13 16:11 UTC, ChristopherDavidDean commented on R/get_units.R
> +#' # Get units within a specified latitude-longitude box
Yup, ditto-ing what Lewis said. You just get whatever column is at that specific co-ordinate pair (and therefore what units are in that column).

2024-06-14 11:26 UTC, bethany-j-allen commented
I made all of the suggested edits, please have a final check and we can merge (the final function review)!

2024-06-14 12:13 UTC, LewisAJones commented
Looks good to me @bethany-j-allen - thanks again!

2024-06-14 12:47 UTC, ChristopherDavidDean approved these changes
Thanks @bethany-j-allen, all looks great to me. Happy to merge!

2024-06-14 13:33 UTC, willgearty approved these changes
Same here, looks great, thanks @bethany-j-allen!

2024-06-14 13:33 UTC, merged