REVIEW: def_drilling_sites()
palaeoverse/rmacrostrat pull request #34
Opened 2024-06-11 17:47 UTC by ChristopherDavidDean

HI @bethany-j-allen, great job on working your way through this :S I gave things a check and had a read of that Sessa paper, and in light of that made a few minor changes to language. Otherwise looks good; some minor formatting sorted.

However, I did discover that when attempting to select drill cores via the expedition (e.g. def_drilling_sites(site = "385")), the entire list of expeditions is returned. This is the same case on the Macrostrat API - it just shows {"success":{"v":2,"license":"CC-BY 4.0","data":[]}} and nothing else. However, I CAN get site 317 to return just that site, which just so happens to be the example used on the Macrostrat API. I've changed the example to use site 317 so that it actually returns something sensible, but the majority of users are not going to have that experience. Not sure what you're thoughts on this are, but probably something else that we should flag to the Macrostrat team.

@willgearty @LewisAJones just clueing you in on this too!

2024-06-11 23:44 UTC, willgearty commented
Hmm, if I go to https://macrostrat.org/api/defs/drilling_sites?site=385 it returns:
```
{"success":{"v":2,"license":"CC-BY 4.0","data":[{"epoch":"DSDP","leg":"43","site":"385","hole":"*","lat":37.3695,"lng":-60.1575,"col_id":2786,"col_group_id":128,"penetration":250,"cored":227.7,"recovered":64,"recovery":28.1,"drilled_interval":22.3,"drilled_intervals":1,"cores":24,"date_started":"10/23/97 13:24","date_finished":"10/23/97 13:24","comments":"","ref_id":14}],"refs":{"14":"DSDP. Deep Sea Drilling Project. 1966. http://www.deepseadrilling.org. "}}}
```

2024-06-12 09:35 UTC, ChristopherDavidDean commented
> Hmm, if I go to https://macrostrat.org/api/defs/drilling_sites?site=385, it returns:
> 
> > {"success":{"v":2,"license":"CC-BY 4.0","data":[{"epoch":"DSDP","leg":"43","site":"385","hole":"*","lat":37.3695,"lng":-60.1575,"col_id":2786,"col_group_id":128,"penetration":250,"cored":227.7,"recovered":64,"recovery":28.1,"drilled_interval":22.3,"drilled_intervals":1,"cores":24,"date_started":"10/23/97 13:24","date_finished":"10/23/97 13:24","comments":"","ref_id":14}],"refs":{"14":"DSDP. Deep Sea Drilling Project. 1966. http://www.deepseadrilling.org. "}}}

Ah sorry! I meant leg/expedition, rather than site! Also mine is behaving differently now anyway, but is still returning every single expedition:

https://macrostrat.org/api/defs/drilling_sites?exp=385

2024-06-12 11:06 UTC, bethany-j-allen commented
In my opinion, it's best to choose an example that works, but any other bugs are not really our problem (although we could notify Macrostrat). So I'm happy to close this, unless anyone else disagrees?

2024-06-12 13:52 UTC, bethany-j-allen approved these changes

2024-06-12 14:25 UTC, willgearty requested changes
Ah, I think the problem is that `exp` isn't a valid argument for the defs/drilling_sites endpoint (but is included in one of the API examples). I believe the correct API argument should be "leg", so we just need to add this argument pair to the `api_names` list.

2024-06-12 14:29 UTC, ChristopherDavidDean commented
> Ah, the problem is that `exp` isn't a valid argument for the defs/drilling_sites endpoint (but is included in one of the API examples). I believe the correct API argument (and therefore R function argument) should be "leg".

Not sure this is quite right; the API kicks back an error when you try to use 'leg'. Leg is the old term that was used for expeditions, so I think it's been changed since that documentation was written.

2024-06-12 14:34 UTC, willgearty commented
Huh, you're right...So the argument docs are out-of-date, but the example docs are up-to-date (with the intent). However, the new `exp` field still doesn't seem to work at all.

I guess in that case we should remove the second example in our docs that doesn't work.

2024-06-12 14:53 UTC, ChristopherDavidDean commented
> Huh, you're right...So the argument docs are out-of-date, but the example docs are up-to-date (with the intent). However, the new `exp` field still doesn't seem to work at all.
> 
> I guess in that case we should remove the second example in our docs that doesn't work? For me, this just returns all sites: https://macrostrat.org/api/defs/drilling_sites?exp=317

Huh, totally weird, I swore I managed to get it to only print the records for 317 yesterday, but both API and function are not working. I'm in agreement with Will; I think if it doesn't work we can't really use it as an example. But otherwise, yes, bugs in Macrostrat are not something we should concern ourselves with, beyond reporting them.

2024-06-12 15:14 UTC, willgearty approved these changes

2024-06-12 15:42 UTC, merged